/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.softech.bookstoremanagement.gui;

import com.softech.bookstoremanagement.database.dao.UsersDao;
import com.softech.bookstoremanagement.database.models.Users;
import java.awt.Cursor;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;
import org.apache.commons.configuration2.Configuration;
import org.apache.commons.configuration2.builder.fluent.Configurations;
import org.apache.commons.configuration2.ex.ConfigurationException;
import org.apache.commons.lang3.StringUtils;

/**
 *
 * @author Admin
 */
public class CashierProfileManagement extends javax.swing.JPanel {

    private String userIdGlobal;
    private boolean verify;
    
    /*
    Application language settings
    */
    private String bundlePath = "com.softech.bookstoremanagement.gui.Bundle";
    private String languageConfigFilePath = "language.properties";

    /**
     * Creates new form CashierProfileManagement
     */
    public CashierProfileManagement() {
        initComponents();
        showProfile();
        this.setLanguage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtPosition = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txpPassword = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txpNewPassword = new javax.swing.JPasswordField();
        txpRetypePassword = new javax.swing.JPasswordField();
        btnReform = new javax.swing.JButton();
        btnSaveProfile = new javax.swing.JButton();
        btnShowProfile = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();

        setBorder(new EmptyBorder(5, 5, 5, 5));
        setPreferredSize(new java.awt.Dimension(1000, 520));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(290, 418));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel5.setMaximumSize(new java.awt.Dimension(32767, 125));
        jPanel5.setPreferredSize(new java.awt.Dimension(290, 125));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/bookstoremanagement/icons/icons8-show-permit-card-93.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel5);

        jPanel6.setPreferredSize(new java.awt.Dimension(290, 260));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/softech/bookstoremanagement/gui/Bundle"); // NOI18N
        jLabel3.setText(bundle.getString("CashierProfileManagement.jLabel3.text")); // NOI18N

        txtPosition.setEditable(false);
        txtPosition.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPosition.setText(bundle.getString("CashierProfileManagement.txtPosition.text")); // NOI18N
        txtPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPositionActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText(bundle.getString("CashierProfileManagement.jLabel4.text")); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText(bundle.getString("CashierProfileManagement.jLabel1.text")); // NOI18N

        txtUserName.setEditable(false);
        txtUserName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText(bundle.getString("CashierProfileManagement.jLabel8.text")); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txpPassword)
                    .addComponent(txtUserName)
                    .addComponent(txtPosition, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txpPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6);

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setPreferredSize(new java.awt.Dimension(600, 442));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel7.setMaximumSize(new java.awt.Dimension(32767, 115));
        jPanel7.setMinimumSize(new java.awt.Dimension(100, 115));
        jPanel7.setPreferredSize(new java.awt.Dimension(698, 125));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/bookstoremanagement/icons/icons8-male-user-93.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(271, 271, 271)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 324, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jPanel3.add(jPanel7);

        jPanel8.setPreferredSize(new java.awt.Dimension(698, 260));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText(bundle.getString("CashierProfileManagement.jLabel6.text")); // NOI18N

        txtFirstName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText(bundle.getString("CashierProfileManagement.jLabel7.text")); // NOI18N

        txtLastName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText(bundle.getString("CashierProfileManagement.jLabel9.text")); // NOI18N

        txtPhone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText(bundle.getString("CashierProfileManagement.jLabel10.text")); // NOI18N

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText(bundle.getString("CashierProfileManagement.jLabel11.text")); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText(bundle.getString("CashierProfileManagement.jLabel12.text")); // NOI18N

        btnReform.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnReform.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/bookstoremanagement/icons/icons8-brush-18.png"))); // NOI18N
        btnReform.setText(bundle.getString("CashierProfileManagement.btnReform.text")); // NOI18N
        btnReform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReformActionPerformed(evt);
            }
        });

        btnSaveProfile.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSaveProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/bookstoremanagement/icons/icons8-save-18.png"))); // NOI18N
        btnSaveProfile.setText(bundle.getString("CashierProfileManagement.btnSaveProfile.text")); // NOI18N
        btnSaveProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveProfileActionPerformed(evt);
            }
        });

        btnShowProfile.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnShowProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/bookstoremanagement/icons/icons8-user-location-18.png"))); // NOI18N
        btnShowProfile.setText(bundle.getString("CashierProfileManagement.btnShowProfile.text")); // NOI18N
        btnShowProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txpNewPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                                .addComponent(txtPhone, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFirstName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtLastName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEmail)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                                    .addComponent(txpRetypePassword)))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(btnReform, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(btnShowProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnSaveProfile)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txpNewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(txpRetypePassword))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnReform)
                            .addComponent(btnSaveProfile)
                            .addComponent(btnShowProfile)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel8);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.setPreferredSize(new java.awt.Dimension(988, 20));
        jPanel4.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 996, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel9.setPreferredSize(new java.awt.Dimension(988, 25));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 996, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowProfileActionPerformed
        // TODO add your handling code here:
        showProfile();
    }//GEN-LAST:event_btnShowProfileActionPerformed

    private void btnReformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReformActionPerformed
        // TODO add your handling code here:
        cleanForm();
    }//GEN-LAST:event_btnReformActionPerformed

    private void btnSaveProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveProfileActionPerformed
        // TODO add your handling code here:
        verify = verifyPassword();
        if (verify) {
            if (validateUpdateUser()) {
                int confirmUpdate = JOptionPane.showConfirmDialog(this, "Are you sure to update the information?", "Update Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (confirmUpdate == JOptionPane.YES_OPTION) {
                    UsersDao usersDao = new UsersDao();
                    Users user = new Users();
                    if (txpNewPassword.getPassword().length > 0) {
                        if (Arrays.equals(txpNewPassword.getPassword(), txpRetypePassword.getPassword())) {
                            user.setUserId(userIdGlobal);
                            user.setUsername(txtUserName.getText().trim());
                            user.setPassword(String.valueOf(txpNewPassword.getPassword()));
                            user.setFirstName(txtFirstName.getText().trim());
                            user.setLastName(txtLastName.getText().trim());
                            user.setEmail(txtEmail.getText().trim());
                            user.setPhone(txtPhone.getText().trim());
                            user.setRole("cashier");
                            try {
                                this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
                                usersDao.updateUser(user);
                                storeUserInfo(user.getUsername());
                                this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                                JOptionPane.showMessageDialog(this, "Update User Successfully", "Update User", JOptionPane.INFORMATION_MESSAGE);
                                //                        reloadAll();
                            } catch (IOException ex) {
                                //                Logger.getLogger(UserManagement.class.getName()).log(Level.SEVERE, null, ex);
                                ex.printStackTrace();
                            } catch (SQLException ex) {
                                //                Logger.getLogger(UserManagement.class.getName()).log(Level.SEVERE, null, ex);
                                ex.printStackTrace();
                            } finally {
                                //                        cleanForm();
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "Please Retype The Correct Password", "Retype Password Warning", JOptionPane.WARNING_MESSAGE);
                        }
                    } else {
                        user.setUserId(userIdGlobal);
                        user.setUsername(txtUserName.getText().trim());
                        //                user.setPassword("");
                        user.setFirstName(txtFirstName.getText().trim());
                        user.setLastName(txtLastName.getText().trim());
                        user.setEmail(txtEmail.getText().trim());
                        user.setPhone(txtPhone.getText().trim());
                        user.setRole("cashier");

                        try {
                            this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
                            usersDao.updateUser(user);
                            storeUserInfo(user.getUsername());
                            this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                            JOptionPane.showMessageDialog(this, "Update User Successfully", "Update User", JOptionPane.INFORMATION_MESSAGE);
                            //                    reloadAll();
                        } catch (IOException ex) {
                            //                Logger.getLogger(UserManagement.class.getName()).log(Level.SEVERE, null, ex);
                            ex.printStackTrace();
                        } catch (SQLException ex) {
                            //                Logger.getLogger(UserManagement.class.getName()).log(Level.SEVERE, null, ex);
                            ex.printStackTrace();
                        } finally {
                            //                    cleanForm();
                        }
                    }
                } else {
                    return;
                }
            } else {
                return;
            }
        } else {
            String password = String.valueOf(txpPassword.getPassword());
            if (password.isEmpty()) {
                
            } else{
                this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                JOptionPane.showMessageDialog(this, "Invalid Account", "Account Warning", JOptionPane.WARNING_MESSAGE);
                this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                System.out.println("Verify: " + verify);    
            }
            
        }
    }//GEN-LAST:event_btnSaveProfileActionPerformed

    private void txtPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPositionActionPerformed

    private void cleanForm() {
        txtFirstName.setText("");
        txtLastName.setText("");
        txtEmail.setText("");
        txtPhone.setText("");
        txpPassword.setText("");
        txpNewPassword.setText("");
        txpRetypePassword.setText("");
    }

    public boolean validateUpdateUser() {
        boolean validated = false;
        StringBuilder warningContent = new StringBuilder();

        String username = txtUserName.getText().trim();
        String newPassword = String.valueOf(txpNewPassword.getPassword());
        String retypePassword = String.valueOf(txpRetypePassword.getPassword());
        String firstName = txtFirstName.getText().trim();
        String lastName = txtLastName.getText().trim();
        String email = txtEmail.getText().trim();
        String phone = txtPhone.getText().trim();

        if (StringUtils.isNotEmpty(newPassword) && !newPassword.equals(retypePassword)) {
            warningContent.append("Retype Passwords Do Not Match\n");
        }
        if (StringUtils.isEmpty(firstName)) {
            warningContent.append("First Name Is Required\n");
        }
        if (StringUtils.isEmpty(lastName)) {
            warningContent.append("Last Name Is Required\n");
        }
        if (StringUtils.isEmpty(email)) {
            warningContent.append("Email Is Required\n");
        }
        Pattern emailPattern = Pattern.compile("^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$", Pattern.CASE_INSENSITIVE);
        Matcher matcherEmail = emailPattern.matcher(email);
        if (matcherEmail.matches() == false) {
            warningContent.append("Please Enter A Valid Email Address\n");
        }
        if (StringUtils.isEmpty(phone)) {
            warningContent.append("Phone Number Is Required\n");
        }
        Pattern phonePattern = Pattern.compile("^\\d{10}");
        Matcher matcherPhone = phonePattern.matcher(phone);
        if (matcherPhone.matches() == false) {
            warningContent.append("Please Enter Digital Characters Only Into Phone Field");
        }
        if (StringUtils.isNotEmpty(warningContent)) {
            JOptionPane.showMessageDialog(this, warningContent, "Create User Warning\n", JOptionPane.WARNING_MESSAGE);
        }
        if (StringUtils.isEmpty(warningContent)) {
            validated = true;
        }
        return validated;
    }

    private boolean verifyPassword() {
        String username = txtUserName.getText().trim();
        String password = String.valueOf(txpPassword.getPassword());
        String role = txtPosition.getText().trim();
        boolean[] validAccount = {false, false};

        StringBuilder stringBuilder = new StringBuilder();
        if (StringUtils.isEmpty(password)) {
            stringBuilder.append("Password is Required!");
            JOptionPane.showMessageDialog(this, stringBuilder, "User Warning", JOptionPane.WARNING_MESSAGE);
        }

        UsersDao usersDao = new UsersDao();
        try {
            this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
            validAccount = usersDao.validatePassword(username, password, role);
            this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            System.out.println("Cashier Valid Password: " + validAccount[0]);
            System.out.println("Cashier Valid Data: " + validAccount[1]);
            System.out.println("Role: " + role);
        } catch (IOException ex) {
//            Logger.getLogger(SignIn.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        } catch (SQLException ex) {
//            Logger.getLogger(SignIn.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }

        if (validAccount[0] && validAccount[1] && role.equals("cashier")) {
            verify = true;
        } else {
            verify = false;
        }
        return verify;
    }

    private void storeUserInfo(String username) {
        UsersDao usersDao = new UsersDao();
        Users resultUser = null;
        try {
            this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
            resultUser = usersDao.searchByUsername(username);
            this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        } catch (IOException ex) {
//            Logger.getLogger(SignIn.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        } catch (SQLException ex) {
//            Logger.getLogger(SignIn.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
        String filePath = "signin_info/signin_info.bin";
        try {
            this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
            FileOutputStream signInInfoFileOut = new FileOutputStream(new File(filePath));
            ObjectOutputStream signInInfoObjOut = new ObjectOutputStream(signInInfoFileOut);

            signInInfoObjOut.writeObject(resultUser);

            signInInfoObjOut.close();
            signInInfoFileOut.close();
            this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        } catch (FileNotFoundException ex) {
//            Logger.getLogger(SignIn.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        } catch (IOException ex) {
//            Logger.getLogger(SignIn.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
    }

    private void showProfile() {
        Users resultUser = new Users();
        String filePath = "signin_info/signin_info.bin";

        try {
            FileInputStream f = new FileInputStream(new File(filePath));
            ObjectInputStream o = new ObjectInputStream(f);
            resultUser = (Users) o.readObject();

            userIdGlobal = resultUser.getUserId();
            txtFirstName.setText(resultUser.getFirstName());
            txtLastName.setText(resultUser.getLastName());
            txtPhone.setText(resultUser.getPhone());
            txtEmail.setText(resultUser.getEmail());
            txtPosition.setText(resultUser.getRole());
            txtUserName.setText(resultUser.getUsername());

            f.close();
            o.close();
        } catch (FileNotFoundException ex) {
            //            Logger.getLogger(SignInUserInfo.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        } catch (IOException ex) {
            //            Logger.getLogger(SignInUserInfo.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        } catch (ClassNotFoundException ex) {
            //            Logger.getLogger(SignInUserInfo.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
    }
    
    public void setLanguage() {
        Locale locale;
        String language = "";
        Configurations languageConfigs = new Configurations();
        
        try {
            Configuration languageConfig = languageConfigs.properties(new File(languageConfigFilePath));
            language = languageConfig.getString("language");
        } catch (ConfigurationException ex) {
//            Logger.getLogger(MainClass.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
        if (language.equals("vi")) {
            locale = new Locale("vi", "VN");
        } else {
            locale = Locale.getDefault();
        }
        
        ResourceBundle resourceBundle = ResourceBundle.getBundle(bundlePath, locale);
        
        jLabel6.setText(resourceBundle.getString("CashierProfileManagement.jLabel6.text"));
        btnShowProfile.setText(resourceBundle.getString("CashierProfileManagement.btnShowProfile.text"));
        jLabel8.setText(resourceBundle.getString("CashierProfileManagement.jLabel8.text"));
        btnSaveProfile.setText(resourceBundle.getString("CashierProfileManagement.btnSaveProfile.text"));
        btnReform.setText(resourceBundle.getString("CashierProfileManagement.btnReform.text"));
        jLabel1.setText(resourceBundle.getString("CashierProfileManagement.jLabel1.text"));
        jLabel4.setText(resourceBundle.getString("CashierProfileManagement.jLabel4.text"));
        jLabel12.setText(resourceBundle.getString("CashierProfileManagement.jLabel12.text"));
        jLabel11.setText(resourceBundle.getString("CashierProfileManagement.jLabel11.text"));
        jLabel3.setText(resourceBundle.getString("CashierProfileManagement.jLabel3.text"));
        jLabel9.setText(resourceBundle.getString("CashierProfileManagement.jLabel9.text"));
        jLabel7.setText(resourceBundle.getString("CashierProfileManagement.jLabel7.text"));
        
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReform;
    private javax.swing.JButton btnSaveProfile;
    private javax.swing.JButton btnShowProfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField txpNewPassword;
    private javax.swing.JPasswordField txpPassword;
    private javax.swing.JPasswordField txpRetypePassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
