/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.softech.bookstoremanagement.gui;

import com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatNordIJTheme;
import com.softech.bookstoremanagement.database.models.Users;
import java.awt.Cursor;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.apache.commons.configuration2.Configuration;
import org.apache.commons.configuration2.FileBasedConfiguration;
import org.apache.commons.configuration2.PropertiesConfiguration;
import org.apache.commons.configuration2.builder.FileBasedConfigurationBuilder;
import org.apache.commons.configuration2.builder.fluent.Configurations;
import org.apache.commons.configuration2.builder.fluent.Parameters;
import org.apache.commons.configuration2.convert.DefaultListDelimiterHandler;
import org.apache.commons.configuration2.ex.ConfigurationException;
import org.apache.commons.lang3.StringUtils;

/**
 *
 * @author Linh
 */
public class ManagerMain extends javax.swing.JFrame {

    // private tab sales statistics 
    private SaleStatistics tabSaleStatistics;

    // private tabs for main tab panel
    private UserManagement tabUserManagement;

    // private tabs for main tab panel
    private ListReceipts tabListReceipts;

    /**
     * Private tabs for the main tab pane
     */
    private BookManagement tabBooksManagement;

    /*
    Application theme
     */
    private String theme;
    private String themeConfigFilePath = "theme.properties";

    private static Users userInfo = null;
    private static String userInfoFilePath = "signin_info/signin_info.bin";

    private static Users readUserInfo(String userInfoFilePath) {
        System.out.println("This is readUserInfo");
        Users userInfo = null;
        try ( FileInputStream f = new FileInputStream(new File(userInfoFilePath));  ObjectInputStream o = new ObjectInputStream(f)) {
            userInfo = (Users) o.readObject();
        } catch (FileNotFoundException ex) {
//            Logger.getLogger(SignInUserInfo.class.getName()).log(Level.SEVERE, null, ex);
            userInfo = null;
            ex.printStackTrace();
        } catch (IOException ex) {
//            Logger.getLogger(SignInUserInfo.class.getName()).log(Level.SEVERE, null, ex);
            userInfo = null;
            ex.printStackTrace();
        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(SignInUserInfo.class.getName()).log(Level.SEVERE, null, ex);
            userInfo = null;
            ex.printStackTrace();
        }
        return userInfo;
    }

    private void writeUserNameToolbar() {
        userInfo = readUserInfo(userInfoFilePath);
        String userFullName = StringUtils.capitalize(userInfo.getRole()) + ": " + userInfo.getFirstName() + " " + userInfo.getLastName();
        lblUserFullName.setText(userFullName);
    }

    /**
     * Creates new form ManagerMain
     */
    public ManagerMain() {
        initComponents();
        writeUserNameToolbar();
        mniLightTheme.setActionCommand("Light");
        mniDarkTheme.setActionCommand("Dark");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dilSignOut = new javax.swing.JDialog();
        radGroupThemes = new javax.swing.ButtonGroup();
        tblManager = new javax.swing.JToolBar();
        bntBookManagement = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        bntReceiptsManagement = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        bntSalesStatstics = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        bntUserManagement = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUserFullName = new javax.swing.JLabel();
        tplManager = new javax.swing.JTabbedPane();
        mnbManager = new javax.swing.JMenuBar();
        mnuSystem = new javax.swing.JMenu();
        mnuThemes = new javax.swing.JMenu();
        mniLightTheme = new javax.swing.JRadioButtonMenuItem();
        mniDarkTheme = new javax.swing.JRadioButtonMenuItem();
        mniSignOut = new javax.swing.JMenuItem();
        mniExit = new javax.swing.JMenuItem();
        mnuManagementTools = new javax.swing.JMenu();
        mniBooksMan = new javax.swing.JMenuItem();
        mniReceiptsMan = new javax.swing.JMenuItem();
        mniSalesStats = new javax.swing.JMenuItem();
        mniUsersMan = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mniAboutUs = new javax.swing.JMenuItem();

        javax.swing.GroupLayout dilSignOutLayout = new javax.swing.GroupLayout(dilSignOut.getContentPane());
        dilSignOut.getContentPane().setLayout(dilSignOutLayout);
        dilSignOutLayout.setHorizontalGroup(
            dilSignOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dilSignOutLayout.setVerticalGroup(
            dilSignOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manager Board");
        setSize(new java.awt.Dimension(1000, 715));

        tblManager.setRollover(true);

        bntBookManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/bookstoremanagement/icons/icons8-bookcase-48.png"))); // NOI18N
        bntBookManagement.setText("Book Management");
        bntBookManagement.setFocusable(false);
        bntBookManagement.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bntBookManagement.setPreferredSize(new java.awt.Dimension(140, 50));
        bntBookManagement.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bntBookManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBookManagementActionPerformed(evt);
            }
        });
        tblManager.add(bntBookManagement);
        tblManager.add(jSeparator3);

        bntReceiptsManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/bookstoremanagement/icons/icons8-bill-48.png"))); // NOI18N
        bntReceiptsManagement.setText("Receipts Management");
        bntReceiptsManagement.setFocusable(false);
        bntReceiptsManagement.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bntReceiptsManagement.setPreferredSize(new java.awt.Dimension(140, 50));
        bntReceiptsManagement.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bntReceiptsManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntReceiptsManagementActionPerformed(evt);
            }
        });
        tblManager.add(bntReceiptsManagement);
        tblManager.add(jSeparator2);

        bntSalesStatstics.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/bookstoremanagement/icons/icons8-statistics-48.png"))); // NOI18N
        bntSalesStatstics.setText("Sale Statistics");
        bntSalesStatstics.setFocusable(false);
        bntSalesStatstics.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bntSalesStatstics.setPreferredSize(new java.awt.Dimension(140, 50));
        bntSalesStatstics.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bntSalesStatstics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalesStatsticsActionPerformed(evt);
            }
        });
        tblManager.add(bntSalesStatstics);
        tblManager.add(jSeparator1);

        bntUserManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/bookstoremanagement/icons/icons8-name-48.png"))); // NOI18N
        bntUserManagement.setText("User Management");
        bntUserManagement.setFocusable(false);
        bntUserManagement.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bntUserManagement.setPreferredSize(new java.awt.Dimension(140, 50));
        bntUserManagement.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bntUserManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntUserManagementActionPerformed(evt);
            }
        });
        tblManager.add(bntUserManagement);
        tblManager.add(jSeparator4);

        jLabel1.setText("Welcome");

        lblUserFullName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblUserFullName))
                .addContainerGap(350, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUserFullName)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        tblManager.add(jPanel1);

        mnuSystem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/bookstoremanagement/icons/icons8-administrative-tools-18.png"))); // NOI18N
        mnuSystem.setText("System");

        mnuThemes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/bookstoremanagement/icons/theme-menu-18.png"))); // NOI18N
        mnuThemes.setText("Themes");

        radGroupThemes.add(mniLightTheme);
        mniLightTheme.setText("Light");
        mniLightTheme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/bookstoremanagement/icons/light-theme-18.png"))); // NOI18N
        mniLightTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLightThemeActionPerformed(evt);
            }
        });
        mnuThemes.add(mniLightTheme);

        radGroupThemes.add(mniDarkTheme);
        mniDarkTheme.setText("Dark");
        mniDarkTheme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/bookstoremanagement/icons/dark-theme-18.png"))); // NOI18N
        mniDarkTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDarkThemeActionPerformed(evt);
            }
        });
        mnuThemes.add(mniDarkTheme);

        mnuSystem.add(mnuThemes);

        mniSignOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/bookstoremanagement/icons/icons8-import-18.png"))); // NOI18N
        mniSignOut.setText("Sign Out");
        mniSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSignOutActionPerformed(evt);
            }
        });
        mnuSystem.add(mniSignOut);

        mniExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/bookstoremanagement/icons/icons8-shutdown-18.png"))); // NOI18N
        mniExit.setText("Exit Application");
        mniExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExitActionPerformed(evt);
            }
        });
        mnuSystem.add(mniExit);

        mnbManager.add(mnuSystem);

        mnuManagementTools.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/bookstoremanagement/icons/icons8-office-18.png"))); // NOI18N
        mnuManagementTools.setText("Management Tools");
        mnuManagementTools.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManagementToolsActionPerformed(evt);
            }
        });

        mniBooksMan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/bookstoremanagement/icons/icons8-bookcase-18.png"))); // NOI18N
        mniBooksMan.setText("Books Management");
        mniBooksMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBooksManActionPerformed(evt);
            }
        });
        mnuManagementTools.add(mniBooksMan);

        mniReceiptsMan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/bookstoremanagement/icons/icons8-bill-18.png"))); // NOI18N
        mniReceiptsMan.setText("Receipts Management");
        mniReceiptsMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniReceiptsManActionPerformed(evt);
            }
        });
        mnuManagementTools.add(mniReceiptsMan);

        mniSalesStats.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/bookstoremanagement/icons/icons8-statistics-18.png"))); // NOI18N
        mniSalesStats.setText("Sales statistics");
        mniSalesStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSalesStatsActionPerformed(evt);
            }
        });
        mnuManagementTools.add(mniSalesStats);

        mniUsersMan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/bookstoremanagement/icons/icons8-name-18.png"))); // NOI18N
        mniUsersMan.setText("Users Management");
        mniUsersMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniUsersManActionPerformed(evt);
            }
        });
        mnuManagementTools.add(mniUsersMan);

        mnbManager.add(mnuManagementTools);

        mnuHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/bookstoremanagement/icons/icons8-help-18.png"))); // NOI18N
        mnuHelp.setText("Help");
        mnuHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHelpActionPerformed(evt);
            }
        });

        mniAboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/bookstoremanagement/icons/icons8-people-working-together-18.png"))); // NOI18N
        mniAboutUs.setText("About Us");
        mniAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAboutUsActionPerformed(evt);
            }
        });
        mnuHelp.add(mniAboutUs);

        mnbManager.add(mnuHelp);

        setJMenuBar(mnbManager);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tblManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tplManager)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tblManager, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tplManager, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuManagementToolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManagementToolsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuManagementToolsActionPerformed

    private void mniBooksManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBooksManActionPerformed
        // TODO add your handling code here:
        if (tabBooksManagement == null) {
            tabBooksManagement = new BookManagement();
            ImageIcon icon = new ImageIcon(getClass().getResource("/com/softech/bookstoremanagement/icons/icons8-bookcase-18.png"));
            tplManager.addTab("Books Management", icon, tabBooksManagement);
        }
        tplManager.setSelectedComponent(tabBooksManagement);
    }//GEN-LAST:event_mniBooksManActionPerformed

    private void mniExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mniExitActionPerformed

    private void bntBookManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBookManagementActionPerformed
        this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        if (tabBooksManagement == null) {
            tabBooksManagement = new BookManagement();
            ImageIcon icon = new ImageIcon(getClass().getResource("/com/softech/bookstoremanagement/icons/icons8-bookcase-18.png"));
            tplManager.addTab("Books Management", icon, tabBooksManagement);
        }
        tplManager.setSelectedComponent(tabBooksManagement);
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_bntBookManagementActionPerformed

    private void bntSalesStatsticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalesStatsticsActionPerformed
        this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        if (tabSaleStatistics == null) {
            tabSaleStatistics = new SaleStatistics();
            ImageIcon icon = new ImageIcon(getClass().getResource("/com/softech/bookstoremanagement/icons/icons8-statistics-18.png"));
            tplManager.addTab("Sales Statistics", icon, tabSaleStatistics);
        }
        tplManager.setSelectedComponent(tabSaleStatistics);
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_bntSalesStatsticsActionPerformed

    private void bntUserManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntUserManagementActionPerformed
        this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        if (tabUserManagement == null) {
            tabUserManagement = new UserManagement();
            ImageIcon icon = new ImageIcon(getClass().getResource("/com/softech/bookstoremanagement/icons/icons8-name-18.png"));
            tplManager.addTab("User Management", icon, tabUserManagement);

        }
        tplManager.setSelectedComponent(tabUserManagement);
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_bntUserManagementActionPerformed

    private void mniUsersManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniUsersManActionPerformed
        if (tabUserManagement == null) {
            tabUserManagement = new UserManagement();
            ImageIcon icon = new ImageIcon(getClass().getResource("/com/softech/bookstoremanagement/icons/icons8-name-18.png"));
            tplManager.addTab("User Management", icon, tabUserManagement);
        }
        tplManager.setSelectedComponent(tabUserManagement);
    }//GEN-LAST:event_mniUsersManActionPerformed

    private void mniReceiptsManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniReceiptsManActionPerformed
        if (tabListReceipts == null) {
            tabListReceipts = new ListReceipts();
            ImageIcon icon = new ImageIcon(getClass().getResource("/com/softech/bookstoremanagement/icons/icons8-bill-18.png"));
            tplManager.addTab("Receipts Management", icon, tabListReceipts);
        }
        tplManager.setSelectedComponent(tabListReceipts);
    }//GEN-LAST:event_mniReceiptsManActionPerformed

    private void bntReceiptsManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntReceiptsManagementActionPerformed
        this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        if (tabListReceipts == null) {
            tabListReceipts = new ListReceipts();
            ImageIcon icon = new ImageIcon(getClass().getResource("/com/softech/bookstoremanagement/icons/icons8-bill-18.png"));
            tplManager.addTab("Receipts Management", icon, tabListReceipts);
        }
        tplManager.setSelectedComponent(tabListReceipts);
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_bntReceiptsManagementActionPerformed

    private void mniSalesStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSalesStatsActionPerformed
        if (tabSaleStatistics == null) {
            tabSaleStatistics = new SaleStatistics();
            ImageIcon icon = new ImageIcon(getClass().getResource("/com/softech/bookstoremanagement/icons/icons8-statistics-18.png"));
            tplManager.addTab("Sale Statistics", icon, tabSaleStatistics);
        }
        tplManager.setSelectedComponent(tabSaleStatistics);
    }//GEN-LAST:event_mniSalesStatsActionPerformed

    private void mnuHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHelpActionPerformed

    }//GEN-LAST:event_mnuHelpActionPerformed

    private void mniAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAboutUsActionPerformed
        // TODO add your handling code here:
        AboutUs aboutUs = new AboutUs(this, true);

        aboutUs.setVisible(true);
    }//GEN-LAST:event_mniAboutUsActionPerformed

    private void mniSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSignOutActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(dilSignOut, "Are you sure?", "Sign Out Confirm", JOptionPane.YES_NO_OPTION);
        if (a == JOptionPane.YES_OPTION) {
            dispose();
            try {
                File file = new File("signin_info/signin_info.bin");
                if (file.delete()) {
                    System.out.println(file.getName() + " is deleted!");
                } else {
                    System.out.println("Delete operation is failed.");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            SignIn logOut = new SignIn();
            logOut.setVisible(true);
        }
    }//GEN-LAST:event_mniSignOutActionPerformed

    private void changeTheme() {
        theme = radGroupThemes.getSelection().getActionCommand();

        try {
            Parameters params = new Parameters();
            FileBasedConfigurationBuilder<FileBasedConfiguration> builder
                    = new FileBasedConfigurationBuilder<FileBasedConfiguration>(PropertiesConfiguration.class)
                            .configure(params.properties()
                                    .setFileName(themeConfigFilePath)
                                    .setListDelimiterHandler(new DefaultListDelimiterHandler(',')));
            Configuration config = builder.getConfiguration();
            config.setProperty("theme", theme.toString());
            builder.save();

        } catch (ConfigurationException ex) {
//            Logger.getLogger(ManagerMain.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
        if (theme.equals("Light")) {
            try {
                UIManager.setLookAndFeel(new FlatArcOrangeIJTheme());
                SwingUtilities.updateComponentTreeUI(this);
                this.pack();
            } catch (UnsupportedLookAndFeelException ex) {
//                Logger.getLogger(ChangeLookAndFeel.class.getName()).log(Level.SEVERE, null, ex);
                ex.printStackTrace();
            }
        } else if (theme.equals("Dark")) {
            try {
                UIManager.setLookAndFeel(new FlatNordIJTheme());
                SwingUtilities.updateComponentTreeUI(this);
                this.pack();
            } catch (UnsupportedLookAndFeelException ex) {
//                Logger.getLogger(ChangeLookAndFeel.class.getName()).log(Level.SEVERE, null, ex);
                ex.printStackTrace();
            }
        }
    }

    private void mniLightThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLightThemeActionPerformed
        // TODO add your handling code here:
        this.changeTheme();
    }//GEN-LAST:event_mniLightThemeActionPerformed

    private void mniDarkThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDarkThemeActionPerformed
        // TODO add your handling code here:
        this.changeTheme();
    }//GEN-LAST:event_mniDarkThemeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ManagerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ManagerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ManagerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ManagerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }

        try {
            /*
            Flatlaf look and feel
             */
            UIManager.setLookAndFeel(new FlatArcOrangeIJTheme());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntBookManagement;
    private javax.swing.JButton bntReceiptsManagement;
    private javax.swing.JButton bntSalesStatstics;
    private javax.swing.JButton bntUserManagement;
    private javax.swing.JDialog dilSignOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JLabel lblUserFullName;
    private javax.swing.JMenuBar mnbManager;
    private javax.swing.JMenuItem mniAboutUs;
    private javax.swing.JMenuItem mniBooksMan;
    private javax.swing.JRadioButtonMenuItem mniDarkTheme;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JRadioButtonMenuItem mniLightTheme;
    private javax.swing.JMenuItem mniReceiptsMan;
    private javax.swing.JMenuItem mniSalesStats;
    private javax.swing.JMenuItem mniSignOut;
    private javax.swing.JMenuItem mniUsersMan;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenu mnuManagementTools;
    private javax.swing.JMenu mnuSystem;
    private javax.swing.JMenu mnuThemes;
    private javax.swing.ButtonGroup radGroupThemes;
    private javax.swing.JToolBar tblManager;
    private javax.swing.JTabbedPane tplManager;
    // End of variables declaration//GEN-END:variables
}
