/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.softech.bookstoremanagement.gui;

import com.softech.bookstoremanagement.database.dao.BooksDao;
import com.softech.bookstoremanagement.database.dao.StatisticsDao;
import com.softech.bookstoremanagement.database.models.Books;
import java.awt.Cursor;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.border.EmptyBorder;
import org.apache.commons.configuration2.Configuration;
import org.apache.commons.configuration2.builder.fluent.Configurations;
import org.apache.commons.configuration2.ex.ConfigurationException;

/**
 *
 * @author Admin
 */
public class SaleStatistics extends javax.swing.JPanel {

    /**
     * Creates new form SaleStatistics
     */
    private HashMap<LocalDate, Float> sevenDaysRevenue = new HashMap<>();
    private HashMap<String, Integer> topFiveBooks = new HashMap<>();
    private String[] bookIds;
    float totalRevenue;
    int bookIndex;
    
     /*
    Application language settings
    */
    private String bundlePath = "com.softech.bookstoremanagement.gui.Bundle";
    private String languageConfigFilePath = "language.properties";

    public SaleStatistics() {        
        bookIndex = 0;
        initComponents();
        this.setLanguage();
        getSaleData();
        exportChartToFile();
        showChartFromFile();
        getTopFiveBooks();
        showBook(bookIndex);        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblChart = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblCoverPhoto = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblAuthor = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblSoldCopies = new javax.swing.JLabel();
        lblCurrentBook = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblPublisher = new javax.swing.JLabel();
        lblPrev = new javax.swing.JLabel();
        lblNext = new javax.swing.JLabel();
        lblTitleContent = new javax.swing.JLabel();
        lblAuthorContent = new javax.swing.JLabel();
        lblPublisherContent = new javax.swing.JLabel();
        lblPriceContent = new javax.swing.JLabel();
        lblSoldContent = new javax.swing.JLabel();

        setBorder(new EmptyBorder(5, 5, 5, 5));
        setPreferredSize(new java.awt.Dimension(1000, 520));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/softech/bookstoremanagement/gui/Bundle"); // NOI18N
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("SaleStatistics.jPanel3.border.title"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblChart, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblChart, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText(bundle.getString("SaleStatistics.jLabel1.text")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("SaleStatistics.jPanel4.border.title"))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCoverPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCoverPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
        );

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTitle.setText(bundle.getString("SaleStatistics.lblTitle.text")); // NOI18N

        lblAuthor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAuthor.setText(bundle.getString("SaleStatistics.lblAuthor.text")); // NOI18N

        lblPrice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPrice.setText(bundle.getString("SaleStatistics.lblPrice.text")); // NOI18N

        lblSoldCopies.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSoldCopies.setText(bundle.getString("SaleStatistics.lblSoldCopies.text")); // NOI18N

        lblCurrentBook.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCurrentBook.setText(bundle.getString("SaleStatistics.lblCurrentBook.text")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText(bundle.getString("SaleStatistics.jLabel4.text")); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText(bundle.getString("SaleStatistics.jLabel5.text")); // NOI18N

        lblPublisher.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPublisher.setText(bundle.getString("SaleStatistics.lblPublisher.text")); // NOI18N

        lblPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/bookstoremanagement/icons/prev_icon_20.png"))); // NOI18N
        lblPrev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPrevMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPrevMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPrevMouseExited(evt);
            }
        });

        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/bookstoremanagement/icons/next_icon_20.png"))); // NOI18N
        lblNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNextMouseExited(evt);
            }
        });

        lblTitleContent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTitleContent.setText(bundle.getString("SaleStatistics.lblTitleContent.text")); // NOI18N

        lblAuthorContent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAuthorContent.setText(bundle.getString("SaleStatistics.lblAuthorContent.text")); // NOI18N

        lblPublisherContent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPublisherContent.setText(bundle.getString("SaleStatistics.lblPublisherContent.text")); // NOI18N

        lblPriceContent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPriceContent.setText(bundle.getString("SaleStatistics.lblPriceContent.text")); // NOI18N

        lblSoldContent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSoldContent.setText(bundle.getString("SaleStatistics.lblSoldContent.text")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblSoldCopies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPublisher, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                            .addComponent(lblAuthor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitleContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAuthorContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPublisherContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPriceContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSoldContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(lblPrev)
                                .addGap(18, 18, 18)
                                .addComponent(lblCurrentBook)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(lblNext))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 31, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(lblTitleContent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAuthor)
                    .addComponent(lblAuthorContent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPublisher)
                    .addComponent(lblPublisherContent))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice)
                    .addComponent(lblPriceContent))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoldCopies)
                    .addComponent(lblSoldContent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNext)
                    .addComponent(lblPrev)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCurrentBook, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblPrevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrevMouseClicked
        // TODO add your handling code here:
        if (bookIndex > 0) {
            bookIndex = bookIndex - 1;
            lblCurrentBook.setText(String.valueOf(bookIndex + 1));
            showBook(bookIndex);
        } else {
            bookIndex = 4;
            lblCurrentBook.setText(String.valueOf(bookIndex + 1));
            showBook(bookIndex);
        }
    }//GEN-LAST:event_lblPrevMouseClicked

    private void lblNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNextMouseClicked
        // TODO add your handling code here:
        if (bookIndex < 4) {
            bookIndex = bookIndex + 1;
            lblCurrentBook.setText(String.valueOf(bookIndex + 1));
            showBook(bookIndex);
        } else {
            bookIndex = 0;
            lblCurrentBook.setText(String.valueOf(bookIndex + 1));
            showBook(bookIndex);
        }
    }//GEN-LAST:event_lblNextMouseClicked

    private void lblNextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNextMouseEntered
        // TODO add your handling code here:
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblNextMouseEntered

    private void lblNextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNextMouseExited
        // TODO add your handling code here:
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_lblNextMouseExited

    private void lblPrevMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrevMouseEntered
        // TODO add your handling code here:
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblPrevMouseEntered

    private void lblPrevMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrevMouseExited
        // TODO add your handling code here:
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_lblPrevMouseExited

    private void getSaleData() {
        StatisticsDao statisticsDao = new StatisticsDao();
        try {
            this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
            sevenDaysRevenue = statisticsDao.searchRevenueLast7Days();
            this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        } catch (IOException ex) {
//            Logger.getLogger(SaleStatistics.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        } catch (SQLException ex) {
//            Logger.getLogger(SaleStatistics.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
    }

    private void exportChartToFile() {
        Set<LocalDate> keyDays = sevenDaysRevenue.keySet();
        LocalDate[] days = new LocalDate[keyDays.size()];
        keyDays.toArray(days);
        String[] daysString = new String[keyDays.size()];
        for (int i = 0; i < daysString.length; i++) {
            daysString[i] = days[i].toString();
        }

        List<Float> revenueList = new ArrayList<>();
        for (LocalDate day : days) {
            float revenueOneDay = sevenDaysRevenue.get(day);
            revenueList.add(revenueOneDay);
        }
        float[] revenueArray = new float[revenueList.size()];
        for (int i = 0; i < revenueArray.length; i++) {
            revenueArray[i] = revenueList.get(i);
            totalRevenue = totalRevenue + revenueArray[i];
        }

        try {
            StatisticsUtils.drawChart(daysString, revenueArray);
        } catch (Exception ex) {
//            Logger.getLogger(SaleStatistics.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }

    }

    private void showChartFromFile() {
        String path = "chart/BarChart.jpeg";
        File chartFile = new File(path);
        java.awt.Image chartImage = null;
        try {
            InputStream chartInputStream = new FileInputStream(chartFile);
            chartImage = ImageIO.read(chartInputStream);
            lblChart.setIcon(new ImageIcon(chartImage));
            jLabel2.setText(String.valueOf("$" + totalRevenue));
        } catch (FileNotFoundException ex) {
//            Logger.getLogger(SaleStatistics.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        } catch (IOException ex) {
//            Logger.getLogger(SaleStatistics.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }

    }

    private void getTopFiveBooks() {
        StatisticsDao statisticsDao = new StatisticsDao();
        try {
            this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
            topFiveBooks = statisticsDao.searchFiveBestSellingBooks();
            this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        } catch (IOException ex) {
//            Logger.getLogger(SaleStatistics.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        } catch (SQLException ex) {
//            Logger.getLogger(SaleStatistics.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
        Set<String> bookIdSet = topFiveBooks.keySet();
        bookIds = new String[bookIdSet.size()];
        bookIdSet.toArray(bookIds);
    }

    private void showBook(int bookIdIndex) {
        String keyId = bookIds[bookIdIndex];
        String soldCopies = topFiveBooks.get(keyId).toString();
        BooksDao booksDao = new BooksDao();
        try {
            this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
            Books book = booksDao.searchById(keyId).get(0);
            this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            String title = book.getTitle();
            String authors = book.getAuthors();
            float price = book.getPrice();
            String publisher = book.getPublisher();
            if (title.length() < 45) {
                lblTitleContent.setText(title);
            } else {
                lblTitleContent.setText(title.substring(0, 45) + "...");
            }
            lblAuthorContent.setText(authors);
            lblPublisherContent.setText(publisher);
            lblPriceContent.setText(String.valueOf(price));
            lblSoldContent.setText(soldCopies);

            ByteArrayInputStream coverPhotoInputStream = new ByteArrayInputStream(book.getCoverPhoto());
            java.awt.Image coverPhoto = null;
            coverPhoto = ImageIO.read(coverPhotoInputStream);
            coverPhoto = coverPhoto.getScaledInstance(296, 296, java.awt.Image.SCALE_SMOOTH);
            ImageIcon coverPhotoIcon = new ImageIcon(coverPhoto);
            lblCoverPhoto.setIcon(coverPhotoIcon);
        } catch (IOException ex) {
//            Logger.getLogger(SaleStatistics.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        } catch (SQLException ex) {
//            Logger.getLogger(SaleStatistics.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }

    }
    
    public void setLanguage() {
        Locale locale;
        String language = "";
        Configurations languageConfigs = new Configurations();
        
        try {
            Configuration languageConfig = languageConfigs.properties(new File(languageConfigFilePath));
            language = languageConfig.getString("language");
        } catch (ConfigurationException ex) {
//            Logger.getLogger(MainClass.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
        if (language.equals("vi")) {
            locale = new Locale("vi", "VN");
        } else {
            locale = Locale.getDefault();
        }
        
        ResourceBundle resourceBundle = ResourceBundle.getBundle(bundlePath, locale);

        lblTitle.setText(resourceBundle.getString("SaleStatistics.lblTitle.text"));
        lblPublisher.setText(resourceBundle.getString("SaleStatistics.lblPublisher.text"));
        jLabel1.setText(resourceBundle.getString("SaleStatistics.jLabel1.text"));
        lblSoldCopies.setText(resourceBundle.getString("SaleStatistics.lblSoldCopies.text"));
        lblPrice.setText(resourceBundle.getString("SaleStatistics.lblPrice.text"));
        lblAuthor.setText(resourceBundle.getString("SaleStatistics.lblAuthor.text"));
              
        
    }

//    public static void main(String[] args) {
//        getSaleData();
//        exportChartToFile();
//        
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblAuthor;
    private javax.swing.JLabel lblAuthorContent;
    private javax.swing.JLabel lblChart;
    private javax.swing.JLabel lblCoverPhoto;
    private javax.swing.JLabel lblCurrentBook;
    private javax.swing.JLabel lblNext;
    private javax.swing.JLabel lblPrev;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblPriceContent;
    private javax.swing.JLabel lblPublisher;
    private javax.swing.JLabel lblPublisherContent;
    private javax.swing.JLabel lblSoldContent;
    private javax.swing.JLabel lblSoldCopies;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitleContent;
    // End of variables declaration//GEN-END:variables
}
